### ISSUE TITLE
[BUG] Megabasterd don't run

### ISSUE THREAD

**Issue by MarcoRavich** [anderlli0053/DEV-tools#314]
Hi there,
I've tryed to get rid of my portable installation of MB but both scoop-extras and your bucket versions lacks of needed Java stuff to run it (included in the official portable version instead): https://github.com/tonikelope/megabasterd/releases/

...can you please fix it ?

Thanks in advance !

**Comment by anderlli0053** [comment]
Hello!

The thing here is that while there is a warning in the manifest file itself that shows when you are trying to install the Megabasterd via Scoop and kind of warns you that in order for it to run you need to have JDK preinstalled:

```
"suggest": {
        "JDK": [
            "java/openjdk",
            "java/oraclejdk"
        ]
    }
```


Because the batch script that this manifest links to, just calls the windowed java executable and points it to external JAR file that resides in the current directory path...

The batch script is created via:

`"pre_install": "Set-Content \"$dir\\MegaBasterd.bat\" '@start javaw.exe -jar \"%~dp0MegaBasterd.jar\" %*' -Encoding Ascii",`



So all in all, i could modify this manifest, but when it gets updated again it, it will get pulled from other buckets and the content will be replaced

I could create an additional manifest that includes all of that including JDK but that will be huge and regarding Oracle's EULA i do not know if one can include their software into any third-party products. I think this is one of the reasons that the Scoop maintainers themselves did not do that in the first place, the second reason being the size of that.

**Comment by MarcoRavich** [comment]
Hi there, thanks for reply.

Of course I don't wanna have JDK preinstalled.

Can't you simply use the @tonikelope's portable pack ?

**Comment by anderlli0053** [comment]
This is fixed and closed by https://github.com/anderlli0053/DEV-tools/issues/314

**Comment by anderlli0053** [comment]
Fixed by https://github.com/anderlli0053/DEV-tools/commit/7e4bbd167dac9f8497f6fdc4d05b680c5346f58a

**Comment by MarcoRavich** [comment]
Just reinstalled from your bucket and still don't work for me.

**Comment by MarcoRavich** [comment]
Ok, I've removed your bucket, readded and now works correctly.
